import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :meddie, MeddieWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# HTTPS termination is handled by the reverse proxy (e.g. Traefik). Phoenix
# serves plain HTTP internally — `force_ssl` here would 301 WebSocket upgrade
# requests when X-Forwarded-Proto isn't set on the upgrade by the proxy.
# If HSTS is needed, set it on the reverse proxy.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
